"""QA team members for issue assignment."""

TEAM: list[dict[str, str]] = [
    {"name": "Adarsha Dinda", "email": "Adarsha.Dinda@ibm.com"},
    {"name": "Aditya Roshan Ramteke", "email": "Aditya.Roshan.Ramteke@ibm.com"},
    {"name": "Aarti Sharma", "email": "saarti@ibm.com"},
    {"name": "Anuchaithra Rao", "email": "Anuchaithra.Rao@ibm.com"},
    {"name": "Anushree Hallur", "email": "Anushree.Hallur@ibm.com"},
    {"name": "Arunkumar Ravindranath", "email": "Arunkumar.Ravindranath@ibm.com"},
    {"name": "Chaitanya Dommeti", "email": "Chaitanya.Dommeti@ibm.com"},
    {"name": "Chaithra Kulal", "email": "Chaithra.Kulal@ibm.com"},
    {"name": "Deepshikha Singh", "email": "Deepshikha.Singh@ibm.com"},
    {"name": "Divya Gowri Pentakota", "email": "DIVYA.GOWRI.PENTAKOTA1@ibm.com"},
    {"name": "Harish Acharya", "email": "Harish.Acharya@ibm.com"},
    {"name": "Harsh Kumar", "email": "Harsh.Kumar9@ibm.com"},
    {"name": "Hemanth Kumar Y J", "email": "Hemanth.Kumar.YJ@ibm.com"},
    {"name": "Hemanth Maheswarla", "email": "Maheswarla.Hemanth.Sai@ibm.com"},
    {"name": "Jaya Prakash P", "email": "jayaprakash.p@ibm.com"},
    {"name": "K Amarnath Reddy", "email": "K.Amarnath.Reddy@ibm.com"},
    {"name": "Kinjal Dhaduk", "email": "Kinjal.Dhaduk@ibm.com"},
    {"name": "Krishna Ramaswamy", "email": "Krishna.Ramaswamy@ibm.com"},
    {"name": "Lahari Mucchala", "email": "Lahari.Mucchala5@ibm.com"},
    {"name": "Madhavi Kasturi", "email": "Kasturi.Venkata.Madhavi@ibm.com"},
    {"name": "Manasa Gowri H S", "email": "Manasa.Gowri.H.S@ibm.com"},
    {"name": "Manan Khanna", "email": "Manan.Khanna1@ibm.com"},
    {"name": "Manimaran M", "email": "manimaran.m@ibm.com"},
    {"name": "Manish Singh", "email": "Manish.Singh29@ibm.com"},
    {"name": "Manisha Reddem", "email": "Manisha.Reddem@ibm.com"},
    {"name": "Manohar M", "email": "Manohar.M@ibm.com"},
    {"name": "Mohit Bisht", "email": "Mohit.Bisht@ibm.com"},
    {"name": "Neha Gangadhar", "email": "Neha.Gangadhar@ibm.com"},
    {"name": "Obanna Komera", "email": "Obanna.Komera@ibm.com"},
    {"name": "Pawan Vinayak Dhiran", "email": "Pawan.Vinayak.Dhiran@ibm.com"},
    {"name": "Pragadeeswaran Sathyanarayanan", "email": "Pragadeeswaran.Sathyanarayanan@ibm.com"},
    {"name": "Rahul Lepakshi", "email": "Rahul.Lepakshi@ibm.com"},
    {"name": "Rakesh Narayan Chilkunda", "email": "rakesh.narayan@ibm.com"},
    {"name": "Sandeep Yadav", "email": "sandeep.y23@ibm.com"},
    {"name": "Sayalee Raut", "email": "Sayalee.Sameer.Raut@ibm.com"},
    {"name": "Shanthakumar Rajan", "email": "Shanthakumar.Rajan@ibm.com"},
    {"name": "Sohan Singh", "email": "Sohan.Singh@ibm.com"},
    {"name": "Srinivasa Bharath Kanta", "email": "Srinivasa.Bharath.Kanta@ibm.com"},
    {"name": "Sunil Angadi", "email": "Sunil.Angadi@ibm.com"},
    {"name": "Sunil Kumar N", "email": "Sunil.Kumar.N2@ibm.com"},
    {"name": "Tejas Chandramouli", "email": "Tejas.Chandramouli@ibm.com"},
    {"name": "Tintu Mathew", "email": "Tintu.Mathew@ibm.com"},
    {"name": "Vaibhav Mahajan", "email": "Vaibhav.Sukhadev.Mahajan@ibm.com"},
    {"name": "Veera Reddy", "email": "B.Veeraraghava.Reddy@ibm.com"},
    {"name": "Venkatesh Ravula", "email": "Venkatesh.Ravula@ibm.com"},
    {"name": "Vidushi Mishra", "email": "Vidushi.Mishra@ibm.com"},
    {"name": "Vidya Lokesh", "email": "vidya.lokesh1@ibm.com"},
    {"name": "Vinayak Papnoi", "email": "Vinayak.Ramesh.Papnoi@ibm.com"},
    {"name": "Vipin M S", "email": "Vipin.M.S@ibm.com"},
    {"name": "Vivek Das", "email": "Vivek.Das@ibm.com"},
    {"name": "Yuri Weinstein", "email": "yweinste@ibm.com"},
    {"name": "Yuva Teja Sree Gayam", "email": "Yuva.Teja.Sree.Gayam@ibm.com"},
]

TEAM_NAMES: list[str] = sorted(m["name"] for m in TEAM)
